version: "3"

services:
  qbittorrentee:
    image: rogunt/qbittorrentee:latest
    container_name: qbittorrentee
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qb/appdata:/config # 配置文件路径，请自行映射
      - ./qb/downloads:/downloads # 下载路径，请自行映射
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
