lzc-sdk-version: "0.1"
name: qBittorrent Enhanced Edition
package: cloud.lazycat.app.qbittorrentee
version: 5.0.3
description: qBittorrent社区增强版
homepage: https://github.com/c0re100/qBittorrent-Enhanced-Edition
author: c0re100
application:
  subdomain: qbittorrentee
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  file_handler:
    mime:
      - application/x-magnet
      - application/x-bittorrent
    actions:
      open: /open?file=%u
  routes:
    - /=http://qbittorrentee.cloud.lazycat.app.qbittorrentee.lzcapp:8080/
  public_path:
    - /
  ingress:
    - protocol: tcp
      port: 6881
      service: qbittorrentee
    - protocol: udp
      port: 6881
      service: qbittorrentee
services:
  qbittorrentee:
    image: registry.lazycat.cloud/czyt/rogunt/qbittorrentee:da1c94111f2a5257
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881

    binds:
      - /lzcapp/var/config:/config
      - /lzcapp/var/downloads:/downloads
