lzc-sdk-version: "0.1"
name: qBittorrent Enhanced Edition
package: cloud.lazycat.app.qbittorrentee
version: 5.0.5.10
description: qBittorrent社区增强版
homepage: https://github.com/czyt/Docker-qBittorrent-Enhanced-Edition
author: czyt
application:
  subdomain: qbittorrentee
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  file_handler:
    mime:
      - application/x-magnet
      - application/x-bittorrent
    actions:
      open: /open?file=%u
  routes:
    - /=http://qbittorrentee:8080/
  public_path:
    - /
  ingress:
    - protocol: tcp
      port: 6881
      service: qbittorrentee
    - protocol: udp
      port: 6881
      service: qbittorrentee
services:
  qbittorrentee:
    image: docker.1ms.run/czyt/qbittorrentee:5.0.5.10
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - ENABLE_DOWNLOADS_PERM_FIX=true

    binds:
      - /lzcapp/var/config:/config
      - /lzcapp/var/downloads:/downloads
