name: qBittorrent Enhanced Edition
package: cloud.lazycat.app.qbittorrentee
min_os_version: 1.3.8
version: 5.1.3
description: qBittorrent社区增强版
homepage: https://github.com/dockers-x/Docker-qBittorrent-Enhanced-Edition
author: czyt
application:
  subdomain: qbittorrentee
  background_task: true
  file_handler:
    mime:
      - application/x-magnet
      - application/x-bittorrent
    actions:
      open: /open?file=%u
  routes:
    - /=http://qbittorrentee:8080/
  public_path:
    - /
  ingress:
    - protocol: tcp
      port: 6881
      service: qbittorrentee
    - protocol: udp
      port: 6881
      service: qbittorrentee
services:
  qbittorrentee:
    # czyt/qbittorrentee:5.1.3.10
    image: registry.lazycat.cloud/czyt/czyt/qbittorrentee:f71ecc9c9a095c4c
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - ENABLE_DOWNLOADS_PERM_FIX=true

    binds:
      - /lzcapp/var/config:/config
      - /lzcapp/var/downloads:/downloads

ext_config:
  enable_document_access: true
  enable_media_access: true
